import { StyleSheet } from "react-native";
import { colors } from "../../Components/Common/Colors";


export const style =(width, height,isProtrait)=> StyleSheet.create({
    main:{
        flex:1,
        padding:10,
        overflow:'hidden',
    },
    contentView:{
        width:"100%",
        flexDirection:'row',
    },
    flatList:{
        width:isProtrait?width*.22:height*.22,
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:colors.secondary_green,
        borderRadius:10,
        paddingBottom:isProtrait?width*.4:height*.3,
    },
    touch:{
        justifyContent:'center', 
        alignItems:'center',
        margin:10,
        padding:10,
        paddingBottom:10,
        borderBottomColor:colors.black_level_3,
        borderBottomWidth:.8,
        borderRadius:10
    },
    image:{
        width:isProtrait?width*.15:height*.15,
        height:isProtrait?width*.15:height*.15,
        resizeMode:'contain'
    },

    // Content Details
    prodctList:{
        justifyContent:'center',
        alignItems:'flex-start',
        marginLeft:10
    },
    bgImage:{
        width:isProtrait?width*.7:width*.8,
        height:isProtrait?width*.3:height*.2,
        resizeMode:'contain',
        borderRadius:10,
        overflow:'hidden',
        
    },
    headText:{
        marginLeft:10,
        fontFamily:'Lato-Bold',
        fontSize:22,
        color:colors.black,
        padding:10,
    },
    descText:{
        marginLeft:10,
        paddingLeft:10,
        fontFamily:'Lato-Regular',
        fontSize:16,
        color:colors.black_level_2,
    },
    proTextHead:{
        width:"100%",
        fontFamily:'Lato-Bold',
        fontSize:14,
        color:colors.black,
    },
    proTextDesc:{
        fontFamily:'Lato-Regular',
        fontSize:14,
    },
    productView:{
        width:isProtrait?width*.7:width*.8,
        flexDirection:'row',
        flexWrap:"wrap",
        paddingBottom:150,
        alignSelf:'center'
    },
    proTouch:{
        width:isProtrait?width*.29:width*.15,
        height:isProtrait?width*.4:width*.23,
        justifyContent:'center',
        alignItems:"center",
        marginVertical:10,
        marginHorizontal:10,
        borderRightWidth:1,
        borderBottomWidth:1,
        borderRadius:10,
        padding:10,
        borderColor:colors.primary_green,
        backgroundColor:colors.light_green,
    },
    proImage:{
        width:isProtrait?width*.17:height*.17,
        height:isProtrait?width*.17:height*.17,
        resizeMode:"contain",
        padding:10,
        alignSelf:'center',
        backgroundColor:colors.secondary_green,
        borderRadius:10,
        marginBottom:10
    },
    emptyBox:{
        width:'100%',
        padding:10,
        backgroundColor:colors.warning,
        marginVertical:10,
        borderRadius:10
    },
    emptyText:{
        fontFamily:'Lato-Bold',
        fontSize:20,
        textAlign:'center',
        color:colors.white
    }
})