import { StyleSheet } from "react-native";
import { colors } from "../../../../Components/Common/Colors";


export const style =(width, height,isProtrait)=> StyleSheet.create({
    main:{
        flex:1,
        justifyContent:'center', 
        alignItems:'center',
        marginBottom:15,
        elevation:20
    },
    coupon:{
        width:isProtrait?width*.95:width*.8,
        height:isProtrait?width*.32:width*.2,
        resizeMode:'cover',
        margin:10,
        flexDirection:'row',
        alignItems:'center'
    },
    offView:{
        flexDirection:'row',
        alignItems:'center',
    },
    offText:{
        fontFamily:'Lato-Bold',
        fontSize:30,
        color:colors.black,
        paddingLeft:isProtrait?35:50
    },
    offSideText:{
        fontFamily:'Lato-Regular',
        fontSize:14,
        color:colors.primary_green,
    },
    contentView:{
        width:isProtrait?'43%':'45%',
        height:'100%',
        borderLeftWidth:1,
        borderLeftColor:colors.primary_green,
        paddingLeft:5,
        justifyContent:'center'
    },
    headText:{
        fontFamily:'Lato-Black',
        fontSize:18,
        color:colors.black_level_2
    },
    descText:{
        fontFamily:'Lato-Regular',
        fontSize:14,
        color:colors.black_level_3
    },
    codeView:{
        paddingLeft:15,
        height:'100%',
        alignItems:'flex-start',
        position:'relative'
    },
    codeText:{
        fontFamily:'Lato-Bold',
        fontSize:18,
        color:colors.black_level_3,
        top:5
    },

    touchView:{
        width:100,
        position:'absolute',
        borderRadius:10,
        backgroundColor:colors.primary_green,
        padding:8,
        bottom:5,
        right:10
    },
    touchText:{
        fontFamily:'Lato-Bold',
        justifyContent:'center', 
        alignItems:'center',
        fontSize:14,
        color:colors.white
    },
    emptyBox:{
        alignContent:'center',
        padding:20,
        backgroundColor:colors.warning,
        borderRadius:10
    },
    emptyText:{
        fontFamily:'Lato-Bold',
        color:colors.white,
        fontSize:18,
        textAlign:'center'
    },
    emptyGotoHome:{
        fontFamily:'Lato-Italic',
        color:colors.primary,
        fontSize:16,
        textAlign:'center',
        marginTop:10
    }
})